[Feature] Added new documentation of the bot refactor
nhcarrigan/discord-bot-documentation pull request #13
Opened 2020-10-11 19:36 UTC by danielsolartech

# Pull Request

## Description:

- Changed the guides from `config.json` to the `config` command.
- Added `invite` and `optout` commands to the list.
- Added a commands guide.

## Screenshots
![Command Guide 1](https://i.imgur.com/5DrzxmS.png)
![Command Guide 2](https://imgur.com/NjNBKmn.png)

## Note
I'm not a native English speaker, if I have some orthographic errors I sorry for that, I'm trying to improve my English level.

## Related Issue:

Closes #12

2020-10-11 21:22 UTC, nhcarrigan requested changes
Some small tweaks.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +        <h2>Manual Commands (60 commands available)</h2>
```suggestion
        <h2>Manual Commands</h2>
```

Let's remove this, to avoid having to update every time a new feature is added.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            to describe what the command will do when its called. This will show into the `help` command.
```suggestion
            `description` - This property is used to set the description of the command,
            or describe what the command will do when its called. This will show in the `help` command.
```
Verbiage.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            values use `&lt;action (action-1/action-2)&gt;`.
```suggestion
            `parameters` - (Optional) - This property is used to define the available parameters of the command.
            This will show in the `help` command. To define an optional parameter use `&lt;?name-of-parameter&gt;`,
            or use `&lt;name-of-parameter&gt;` if the parameter is required. When a parameter has specific
            values use `&lt;action (action-1/action-2)&gt;`.
```
Verbiage

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            `run` - This property is the actioner of the command, in this you set what the command will do when its called.
```suggestion
            `run` - This property is the action the command takes. In this you set what the command will do when called.
```
Verbiage

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            parameter that we require (Message).
```suggestion
            First, replace the `console.log` line with `const { channel, commandArguments } = message;`. With this you will get 
            the arguments of the command, or the content of the message split by whitespaces and ignoring the
            first element (The first element is the command name), and the channel of the message.
            Now, add `const msg = commandArguments.join(" ");` to join the arguments with whitespaces to get the
            parameter that we require (Message).
```
Verbiage. Also, `<br>` tags are inaccessible and do not work well with screen readers, so should be avoided.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            </code></pre>
```suggestion
            <pre><code style="white-space: pre-wrap;">
              import CommandInt from "@Interfaces/CommandInt";
              const messageRepeater: CommandInt = {
                name: "messageRepeater",
                description: "Send a message to the current channel using the bot.",
                parameters: ["&lt;message&gt;: Message to send."],
                run: async (message) => {
                  console.log("Message repeater command called!");
                },
              };
              export default messageRepeater;
            </code></pre>
```
No `<br>` tags.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            in the chat write `{prefix}messageRepeater` and in the console you will see `Message repeater command called!`.
```suggestion
            Save the file, start the bot (You can use `npm run dev` instead of `npm run build && npm start`), then
            in the chat write `{prefix}messageRepeater` and in the console you will see `Message repeater command called!`.            
```
Verbiage.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            do what we want.<br><br>
```suggestion
            So, to this moment you have created a simple command that shows you a message in the console, but it does not
            do what we want.
```

No `<br>` tags.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            lines below before the `await channel.send(msg);`:
```suggestion
            After you get the message, you need to send it back to the current channel. To do this, add this line:
            `await channel.send(msg);`. Now you can test the command! If you write `{prefix}messageRepeater Hello` in the channel, the bot
            will send `Hello` back to the current channel. But what will happen if you send `{prefix}messageRepeater`? You will
            get an error in the console because the bot cannot send an empty message. So howdo you fix it?
            You need to verify the command arguments have a length before sending the message. Add these
            lines below before the `await channel.send(msg);`:
```
Verbiage, remove `<br>` tags.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            </code></pre>
```suggestion
            <pre><code style="white-space: pre-wrap;">
              if (!msg.length) {
                await message.reply('Sorry, but you must enter a valid message.');
                return;
              }
            </code></pre>
```
No `<br>` tags.

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +            Now, when you call the command with an empty message you receive a message saying you need enter a message.
```suggestion
            Now when you call the command with an empty message the bot will respond with a message saying you need to enter a message.
```
Verbiage

2020-10-11 21:22 UTC, nhcarrigan commented on index.html
> +          </li>
```suggestion
          <li>
            Congratulations! You have written your first command for the bot. We hope you are motivated to contribute to
            the project with more commands or fixes.
          </li>
```
Verbiage.

2020-10-12 05:11 UTC, danielsolartech commented on index.html
> +            </code></pre>
Without the `<br>` the code does not go to the next line

2020-10-12 18:17 UTC, nhcarrigan approved these changes
LGTM~! 🥳 

@all-contributors please add @danielsolartech for code

2020-10-12 18:17 UTC, merged

2020-10-12 18:18 UTC, nhcarrigan commented
@all-contributors please add @danielsolartech for code